### ISSUE TITLE
Suggested feature: status tracking of orders

### ISSUE THREAD

**Issue by ethanheppner** [18F/C2#492]
The story behind this one: our only 18F P-Card holder has been on leave and people have been wondering about the status of their already approved Communicart requests. Is there a way to easily integrate an order status tracker so we can see if approved purchases have been ordered? Maybe it would include a link to a shipping number that users can verify?

**Comment by colinpmacarthur** [comment]
+1

**Comment by phirefly** [comment]
We have a story. Let me know if this captures the idea correctly: https://www.pivotaltracker.com/story/show/98295520

**Comment by phirefly** [comment]
For now, KC is adding a comment if she orders it. That's the only way to tell in the current system. That story will take the next step though.

**Comment by jenniferthibault** [comment]
A sub-story to the story above:
I placed a request for supplies for the 18F NYC office, and the P-card holder is in DC. Since the shipping to our building is still a little untrusted, I'd like to be able to see when the order was actually placed, shipped, and delivered, so that we can keep an eye out for it. It would be great to be able to do this as the order requester, so that I don't have to bother the P-card holder about it.

**Comment by ethanheppner** [comment]
@phirefly : yes, that's a good workaround for now. I'll do the same once I get my P-card.

**Comment by jessieay** [comment]
There is a story for adding "purchased" state to 18F procurements: https://www.pivotaltracker.com/story/show/106244512

Going to close this issue for now since we are now tracking work via Tracker.
